### ISSUE TITLE
I can not use disnixos command.

### ISSUE THREAD

**Issue by 10long** [svanderburg/disnix-stafftracker-php-example#1]
hi 

I want to use disnixos command as follows.
" disnixos-env -s services.nix -n network.nix -d distribution.nix --use-nixops"

but, Error such as the following occurred.
"error: while evaluating the attribute ‘manifestXML’ of the derivation ‘manifest.xml’ at /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/manifest.nix:22:3:
while evaluating ‘generateServiceHashKey’ at /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:229:47, called from /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:287:18:
while evaluating the attribute ‘service’ at /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:195:19:
while evaluating ‘evaluateService’ at /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:144:47, called from /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:195:29:
while evaluating ‘selectPkgProperty’ at /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:129:80, called from /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:193:25:
while evaluating the attribute ‘pkg’ at /home/kametaro/projects/disnix_sample/disnix-stafftracker-php-example/deployment/DistributedDeployment/services.nix:10:5:
while evaluating the attribute ‘rooms’ at /home/kametaro/projects/disnix_sample/disnix-stafftracker-php-example/deployment/top-level/all-packages.nix:9:5:
while evaluating ‘selectPkgs’ at /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:29:16, called from /nix/store/g561lhc8b4gpmklr8a6fki9ss250wc40-disnix-0.6/share/disnix/lib.nix:130:102:
while evaluating the file ‘/nix/store/z0izfn862p0d3anw3q5na8p2g9kgipki-infrastructure.nix’:
opening file ‘/nix/store/default.nix’: No such file or directory"

Please tell me the advice to become a clue of problem-solving.

My machine of the environment are as follows:
os : nixos-16.03
nix-channels
  sudo nix-channel --list
  nixos https://nixos.org/channels/nixos-16.03
  nixpkgs https://nixos.org/channels/nixpkgs-unstable
  nixos_15_09 https://nixos.org/channels/nixos-15.09

nix-env -q
  disnix-0.6
  disnixos-0.5
  dysnomia-0.6
  libxml2-2.9.4
  libxslt-1.1.28
  nix-1.11.2
  nixops-1.3.1

Thanks.

**Comment by svanderburg** [comment]
Hmm this is strange. I just encounted the same problem when using Disnix in conjunction with Nixpkgs directly from the channels.

However, if I would change the NIX_PATH environment variable to refer to a Nixpkgs checkout, e.g.

```
$ export NIX_PATH=nixpkgs=/home/sander/nixpkgs:nixos=/home/sander/nixpkgs/nixos
```

then everything seems to work fine.

**Comment by 10long** [comment]
Thank you for the advice. 
I was able to be resolved!

First, I check my NIX_PATH environment setting. so They had become the designated root user.
Because I was using disnix command in extraUser, it was also to add the channel to the user.
And, just like you, I have been added to the "nixpkgs = /home/my/channels/path" to NIX_PATH.

 Thanks a lot.
